# https://help.github.com/articles/using-jekyll-with-pages
safe:        true
auto:        true
server:      true
server_port: 4000
baseurl:     /
url:         http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ['Gemfile', 'Gemfile.lock']

lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   date

redcarpet:
  extensions: []
